databases:
  - name: smart-warehouse-db
    plan: free
    databaseName: smart_warehouse
    user: smart_warehouse_user

services:
  - type: web
    name: smart-warehouse
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_warehouse.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-warehouse-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.12.13"
