# Generated by Django 5.0.4 on 2026-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("in_production", "Ishlab chiqarishda"),
                    ("completed", "Yakunlangan"),
                    ("cancelled", "Bekor qilingan"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="stage_name",
            field=models.CharField(
                choices=[
                    ("preparation", "Tayyorgarlik"),
                    ("manufacturing", "Ishlab chiqarish"),
                    ("quality_check", "Sifat nazorati"),
                    ("packaging", "Qadoqlash"),
                    ("finished", "Tayyor"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("in_progress", "Jarayonda"),
                    ("completed", "Yakunlangan"),
                    ("skipped", "O'tkazib yuborilgan"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
