# Generated by Django 5.0.4 on 2026-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Kam qoldiq ogohlantirishi"),
                    ("production_complete", "Ishlab chiqarish yakunlandi"),
                    ("insufficient_materials", "Material yetarli emas"),
                    ("general", "Umumiy"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
