# Generated by Django 5.0.4 on 2026-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("warehouse_manager", "Ombor boshqaruvchisi"),
                    ("production_manager", "Ishlab chiqarish boshqaruvchisi"),
                    ("worker", "Ishchi"),
                ],
                default="worker",
                max_length=30,
            ),
        ),
    ]
