# Generated by Django 5.0.4 on 2026-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("IN", "Kirim"),
                    ("OUT", "Chiqim"),
                    ("TRANSFER", "Ko'chirish"),
                    ("ADJUSTMENT", "Tuzatish"),
                    ("PRODUCTION", "Ishlab chiqarishga sarflash"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Dona"),
                    ("kg", "Kilogramm"),
                    ("g", "Gramm"),
                    ("l", "Litr"),
                    ("ml", "Millilitr"),
                    ("m", "Metr"),
                    ("m2", "Kv. metr"),
                    ("m3", "Kub metr"),
                    ("box", "Quti"),
                    ("pack", "Paket"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pcs", "Dona"),
                    ("kg", "Kilogramm"),
                    ("g", "Gramm"),
                    ("l", "Litr"),
                    ("ml", "Millilitr"),
                    ("m", "Metr"),
                    ("m2", "Kv. metr"),
                    ("m3", "Kub metr"),
                    ("box", "Quti"),
                    ("pack", "Paket"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
