# Generated by Django 5.1 on 2026-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorytransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50, unique=True, verbose_name="MXIK"),
        ),
    ]
